CREATE DATABASE [DB_STORE]
GO

USE [DB_STORE]
GO
/****** Object:  Table [dbo].[TB_CARRINHO]    Script Date: 02/11/2019 20:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_CARRINHO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_CLIENTE] [int] NOT NULL,
	[DATA_COMPRA] [datetime] NOT NULL,
	[VALOR_TOTAL] [decimal](15, 2) NULL,
 CONSTRAINT [PK_CARRINHO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_CARRINHO_PRODUTO]    Script Date: 02/11/2019 20:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_CARRINHO_PRODUTO](
	[ID_PRODUTO] [int] NOT NULL,
	[ID_CARRINHO] [int] NOT NULL,
	[QUANTIDADE] [int] NOT NULL,
 CONSTRAINT [PK_CARRINHO_PRODUTO] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUTO] ASC,
	[ID_CARRINHO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_CATEGORIA]    Script Date: 02/11/2019 20:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_CATEGORIA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_CATEGORIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_CLIENTE]    Script Date: 02/11/2019 20:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_CLIENTE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](120) NOT NULL,
	[CPF] [varchar](11) NOT NULL,
	[EMAIL] [varchar](150) NOT NULL,
	[SENHA] [varchar](max) NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_PRODUTO]    Script Date: 02/11/2019 20:21:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_PRODUTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](150) NOT NULL,
	[DESCRICAO] [varchar](500) NULL,
	[VALOR] [decimal](15, 2) NULL,
	[IMAGEM] [varchar](max) NULL,
	[ID_CATEGORIA] [int] NOT NULL,
 CONSTRAINT [PK_PRODUTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[TB_CARRINHO] ON 
GO
INSERT [dbo].[TB_CARRINHO] ([ID], [ID_CLIENTE], [DATA_COMPRA], [VALOR_TOTAL]) VALUES (2, 1, CAST(N'2019-11-01T23:01:41.047' AS DateTime), CAST(3777.00 AS Decimal(15, 2)))
GO
SET IDENTITY_INSERT [dbo].[TB_CARRINHO] OFF
GO
INSERT [dbo].[TB_CARRINHO_PRODUTO] ([ID_PRODUTO], [ID_CARRINHO], [QUANTIDADE]) VALUES (1, 2, 2)
GO
INSERT [dbo].[TB_CARRINHO_PRODUTO] ([ID_PRODUTO], [ID_CARRINHO], [QUANTIDADE]) VALUES (2, 2, 1)
GO
SET IDENTITY_INSERT [dbo].[TB_CATEGORIA] ON 
GO
INSERT [dbo].[TB_CATEGORIA] ([ID], [DESCRICAO]) VALUES (1, N'TV')
GO
INSERT [dbo].[TB_CATEGORIA] ([ID], [DESCRICAO]) VALUES (2, N'Informatica')
GO
INSERT [dbo].[TB_CATEGORIA] ([ID], [DESCRICAO]) VALUES (3, N'Games')
GO
SET IDENTITY_INSERT [dbo].[TB_CATEGORIA] OFF
GO
SET IDENTITY_INSERT [dbo].[TB_CLIENTE] ON 
GO
INSERT [dbo].[TB_CLIENTE] ([ID], [NOME], [CPF], [EMAIL], [SENHA]) VALUES (1, N'Diego de Souza', N'11111111111', N'diego_1souza@hotmail.com', N'078C007BD92DDEC308AE2F5115C1775D')
GO
SET IDENTITY_INSERT [dbo].[TB_CLIENTE] OFF
GO
SET IDENTITY_INSERT [dbo].[TB_PRODUTO] ON 
GO
INSERT [dbo].[TB_PRODUTO] ([ID], [NOME], [DESCRICAO], [VALOR], [IMAGEM], [ID_CATEGORIA]) VALUES (1, N'Smart TV LED 32 HD Samsung 32J4290', N'Smart TV LED 32 HD Samsung 32J4290 com Plataforma Tizen, Wide Color Enhancer Plus, Espelhamento de Tela, Wi-Fi, Dolby Digital Plus, HDMI e USB', CAST(889.00 AS Decimal(15, 2)), NULL, 1)
GO
INSERT [dbo].[TB_PRODUTO] ([ID], [NOME], [DESCRICAO], [VALOR], [IMAGEM], [ID_CATEGORIA]) VALUES (2, N'Smart TV LED 50" Samsung', N'Smart TV LED 50" Samsung UN50RU7100GXZD, 4K HDR, Wi-Fi, USB, HDMI, Bluetooth, 60Hz', CAST(1999.00 AS Decimal(15, 2)), NULL, 1)
GO
INSERT [dbo].[TB_PRODUTO] ([ID], [NOME], [DESCRICAO], [VALOR], [IMAGEM], [ID_CATEGORIA]) VALUES (3, N'Nes Retro', N'Nes Retro Video Game Console 660 Jogos Eua Plug', CAST(118.28 AS Decimal(15, 2)), NULL, 3)
GO
SET IDENTITY_INSERT [dbo].[TB_PRODUTO] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ_EMAIL]    Script Date: 02/11/2019 20:21:18 ******/
ALTER TABLE [dbo].[TB_CLIENTE] ADD  CONSTRAINT [UQ_EMAIL] UNIQUE NONCLUSTERED 
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TB_CARRINHO]  WITH CHECK ADD  CONSTRAINT [FK_CARRINHO_CLIENTE] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[TB_CLIENTE] ([ID])
GO
ALTER TABLE [dbo].[TB_CARRINHO] CHECK CONSTRAINT [FK_CARRINHO_CLIENTE]
GO
ALTER TABLE [dbo].[TB_CARRINHO_PRODUTO]  WITH CHECK ADD  CONSTRAINT [FK_CARRINHO_PRODUTO_CARRINHGO] FOREIGN KEY([ID_CARRINHO])
REFERENCES [dbo].[TB_CARRINHO] ([ID])
GO
ALTER TABLE [dbo].[TB_CARRINHO_PRODUTO] CHECK CONSTRAINT [FK_CARRINHO_PRODUTO_CARRINHGO]
GO
ALTER TABLE [dbo].[TB_CARRINHO_PRODUTO]  WITH CHECK ADD  CONSTRAINT [FK_CARRINHO_PRODUTO_PRODUTO] FOREIGN KEY([ID_PRODUTO])
REFERENCES [dbo].[TB_PRODUTO] ([ID])
GO
ALTER TABLE [dbo].[TB_CARRINHO_PRODUTO] CHECK CONSTRAINT [FK_CARRINHO_PRODUTO_PRODUTO]
GO
ALTER TABLE [dbo].[TB_PRODUTO]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTO_CATEGORIA] FOREIGN KEY([ID_CATEGORIA])
REFERENCES [dbo].[TB_CATEGORIA] ([ID])
GO
ALTER TABLE [dbo].[TB_PRODUTO] CHECK CONSTRAINT [FK_PRODUTO_CATEGORIA]
GO
